# =========================================
# Full Name : 
# =========================================
firstname = Riya
lastname = Patel

# =========================================
# Booking Entry : 
# =========================================
# CCYY-MM-DD
# CC (Century): Represents the first two digits of the year (e.g., 20 for the 2000s).
# YY (Year): Represents the specific year within that century (e.g., 26 for 2026).
# MM (Month): Represents the 2-digit month, from 01 (January) to 12 (December).
# DD (Day): Represents the 2-digit day of the month, from 01 to 31
#

checkin = 2026-07-28
checkout = 2026-07-30