
# =========================================
# Credentials : 
# =========================================
email = student@example.com
password = secret123

token = 


# ==========================================
# EventHub API - Common Configuration
# ==========================================

# Environment
environment=qa

# API Base URL
base.url=https://api.eventhub.rahulshettyacademy.

booking.baseUrl =https://restful-booker.herokuapp.com
		
# API Version
api.version=v1

# Request Timeout (milliseconds)
request.timeout=30000

# Connection Timeout (milliseconds)
connection.timeout=30000

# Socket Timeout (milliseconds)
socket.timeout=30000

# Logging
logging.enabled=true
log.request=true
log.response=true

# Reporting
report.enabled=true

# Parallel Execution
parallel.execution=false
thread.count=1

