# Enable the HTML Spark reporter
extent.reporter.spark.start = true
extent.reporter.spark.out = /Rest_Assured_POM_Framework/reports/ExtentSpark.html


# Optional: Enable PDF reporter
extent.reporter.spark.pdf.start= true
extent.reporter.spark.out = /Rest_Assured_POM_Framework/reports/ExtentReportPdf.pdf



# Screenshot setup for failed steps
screenshot.dir=/Rest_Assured_POM_Framework/screenshots/
screenshot.rel.path=../screenshots/